name: dreamsteps
description: A fully offline Flutter app for tracking dreams and goals.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Animations
  lottie: ^3.1.0
  
  # Fonts
  google_fonts: ^6.1.0

  # Notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  
  # App info
  package_info_plus: ^8.0.0
  
  # Google Ads
  google_mobile_ads: ^5.1.0
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/json/
    - assets/animations/
    - assets/images/
    - assets/icons/
    - assets/dummy_ads/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 26
  adaptive_icon_background: "#4C6EF5"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  remove_alpha_ios: true

